import os
import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage

def generate_pdf_report(data, output_path):
    """
    Generates a PDF tire analysis report.
    :param data: Dictionary containing 'prediction', 'confidence', 'date', 'email', 'conclusion', etc.
    :param output_path: Path where the PDF should be saved.
    """
    doc = SimpleDocTemplate(output_path, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm, topMargin=1.5*cm)
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle(
        "SafeTreadTitle", 
        parent=styles["Title"], 
        fontSize=22, 
        textColor=colors.HexColor("#1A365D"),
        spaceAfter=20
    )
    
    header_style = ParagraphStyle(
        "SafeTreadHeader", 
        parent=styles["Heading2"], 
        fontSize=14, 
        textColor=colors.HexColor("#2D3748"),
        spaceAfter=12
    )
    
    body_style = styles["Normal"]
    body_style.fontSize = 11
    
    story = []
    
    # 1. Header
    story.append(Paragraph("SafeTread Tire Analysis Report", title_style))
    story.append(Spacer(1, 0.5*cm))
    
    # 2. Key Information Table
    date_val = data.get("date", datetime.datetime.now().strftime("%Y-%m-%d"))
    table_data = [
        [Paragraph("<b>User Information</b>", header_style), ""],
        ["User Email:", data.get("email", "N/A")],
        ["Scan Date:", date_val],
        [Spacer(1, 0.2*cm), ""],
        [Paragraph("<b>Analysis Results</b>", header_style), ""],
        ["Prediction Result:", data.get("prediction", "Unknown")],
        ["Confidence Score:", f"{data.get('confidence', 0)}%"],
        ["Conclusion:", Paragraph(f"<b>{data.get('conclusion', 'N/A')}</b>", body_style)],
    ]
    
    summary_table = Table(table_data, colWidths=[5*cm, 10*cm])
    summary_table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('SPAN', (0, 0), (1, 0)), # Span header
        ('SPAN', (0, 4), (1, 4)), # Span header
    ]))
    
    story.append(summary_table)
    story.append(Spacer(1, 1*cm))
    
    # 3. Disclaimer / Conclusion
    story.append(Paragraph("<b>Detailed Conclusion:</b>", header_style))
    conclusion_text = data.get("conclusion", "")
    if "Replace" in conclusion_text or "Worn" in data.get("prediction", ""):
        advise = "Warning: Significant tire wear detected. We strongly recommend visiting a professional tire service for a replacement or detailed inspection to ensure road safety."
    else:
        advise = "Your tires appear to be in healthy condition. Continue periodic checks to ensure optimal performance."
    
    story.append(Paragraph(advise, body_style))
    story.append(Spacer(1, 2*cm))
    
    # 4. Footer
    footer_text = "This report was automatically generated by SafeTread AI Analysis System. This is an AI-assisted determination and should be verified by a certified mechanic if you have safety concerns."
    story.append(Paragraph(f"<i>{footer_text}</i>", ParagraphStyle("Footer", parent=body_style, fontSize=8, textColor=colors.grey)))
    
    doc.build(story)
    return output_path
